// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SomNet.API.Data;

#nullable disable

namespace SomNet.API.Data.Migrations
{
    [DbContext(typeof(SomNetDbContext))]
    [Migration("20260904221800_AddUsers")]
    partial class AddUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SomNet.API.Data.Entities.NotificationHistoryEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("DomTarget")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("SessionDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("SubTarget")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("DomTarget", "SubTarget", "SentAt");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("SomNet.API.Data.Entities.SessionHistoryEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("DomTarget")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Mode")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("SubTarget")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("DomTarget", "SubTarget", "StartedAt");

                    b.ToTable("Sessions", (string)null);
                });

            modelBuilder.Entity("SomNet.API.Data.Entities.User", b =>
                {
                    b.Property<string>("Username")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Username");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("SomNet.API.Data.Entities.UserOptions", b =>
                {
                    b.Property<string>("Username")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("AutoExpandVideoOnMobile")
                        .HasColumnType("bit");

                    b.Property<bool>("ConfirmBeforeCommands")
                        .HasColumnType("bit");

                    b.Property<string>("DefaultNotesPrefix")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("EnableSoundAlerts")
                        .HasColumnType("bit");

                    b.Property<int>("MobileVideoExpandDefault")
                        .HasColumnType("int");

                    b.Property<string>("OperatorDisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("ReconnectIntervalSeconds")
                        .HasColumnType("int");

                    b.Property<bool>("ShowSessionTimestamps")
                        .HasColumnType("bit");

                    b.HasKey("Username");

                    b.ToTable("UserOptions", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
