// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SomNet.API.Data;

#nullable disable

namespace SomNet.API.Data.Migrations
{
    [DbContext(typeof(SomNetDbContext))]
    [Migration("20260905003715_AddSubDeviceRegistrations")]
    partial class AddSubDeviceRegistrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SomNet.API.Data.Entities.DomSubAssignment", b =>
                {
                    b.Property<string>("DomTarget")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("SubName")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("DomTarget", "SubName");

                    b.ToTable("DomSubAssignments", (string)null);
                });

            modelBuilder.Entity("SomNet.API.Data.Entities.DomSubExclusion", b =>
                {
                    b.Property<string>("DomTarget")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("SubName")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("DomTarget", "SubName");

                    b.ToTable("DomSubExclusions", (string)null);
                });

            modelBuilder.Entity("SomNet.API.Data.Entities.DomSubSettings", b =>
                {
                    b.Property<string>("DomTarget")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("SubName")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DomTarget", "SubName");

                    b.ToTable("DomSubSettings", (string)null);
                });

            modelBuilder.Entity("SomNet.API.Data.Entities.NotificationHistoryEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("DomTarget")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("SessionDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("SubTarget")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("DomTarget", "SubTarget", "SentAt");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("SomNet.API.Data.Entities.SessionHistoryEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("DomTarget")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Mode")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("SubTarget")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("DomTarget", "SubTarget", "StartedAt");

                    b.ToTable("Sessions", (string)null);
                });

            modelBuilder.Entity("SomNet.API.Data.Entities.SubDeviceRegistration", b =>
                {
                    b.Property<string>("DomTarget")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("SubName")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastConnectedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("PairedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("TokenExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TokenJti")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("DomTarget", "SubName");

                    b.HasIndex("DeviceId");

                    b.ToTable("SubDeviceRegistrations", (string)null);
                });

            modelBuilder.Entity("SomNet.API.Data.Entities.User", b =>
                {
                    b.Property<string>("Username")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Username");

                    b.ToTable("Users", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
